version: '3.9'
services:
  host:
    build: 
      context: host
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    links:
      - mf_cards
      - mf_counter
      - mf_navbar
  mf_cards:
    build: 
      context: mf-cards
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
  mf_counter:
    build: 
      context: mf-counter
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
  mf_navbar:
    build: 
      context: mf-navbar
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"